[package]
name = "argon2-password"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
argon2 = { version = "0.5.3", features = ["rand", "simple", "std", "zeroize"] }
base64 = "0.22.1"
getrandom = "0.2.15"
